spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
  application:
    name: IDENTITY-SERVICE


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


server:
  port: 9898

management:
  tracing:
    sampling:
      probability: 1.0




