spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
  application:
    name: IDENTITY-SERVICE
  web:
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE
      allowed-headers: "*"
  data:
    redis:
      timeout: 2000ms
      host: localhost
      password:
      port: 6379
      database: 0

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


server:
  port: 9898

management:
  tracing:
    sampling:
      probability: 1.0




# Redis Configuration
# Rate Limiting Configuration
rate-limit:
  key-prefix: "rate_limit:"
  window-size-in-seconds: 300  # 5 minutes

  auth-endpoints:
    login-capacity: 5          # 5 login attempts per window
    login-refill-rate: 1       # 1 token per minute
    register-capacity: 3       # 3 registrations per window
    register-refill-rate: 1    # 1 token per minute
    otp-capacity: 10           # 10 OTP requests per window
    otp-refill-rate: 2         # 2 tokens per minute
    general-capacity: 50       # General auth operations
    general-refill-rate: 10    # 10 tokens per minute

  department-endpoints:
    read-capacity: 100         # 100 read operations per window
    read-refill-rate: 20       # 20 tokens per minute
    write-capacity: 20         # 20 write operations per window
    write-refill-rate: 4       # 4 tokens per minute